format = """
$directory\
[ ](fg:#88C0D0 bg:#2e3440)\
$git_branch\
$git_status\
[ ](fg:#2e3440)\
\n$character
"""

right_format = """
$cmd_duration\
$username\
$time
"""

# コマンドラインに1行分のスペースを入れる
add_newline = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false


# left_promptとright_promptの間を何で埋めるか設定
[fill]
symbol = ' '

[directory]
style = "fg:#2E3440 bg:#88C0D0 bold"
# format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
# truncation_symbol = ' ' # nf-fa-folder_open
# truncate_to_repo = false
# style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[ $path ]($style)[$read_only]($read_only_style)'


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = "󰘬"
style = "bg:#2e3440"
truncation_length = 30
truncation_symbol = "…"
format = '[[ $symbol $branch ](fg:#81a1c1 bg:#2e3440 bold)]($style)'

[git_status]
style = "bg:#2e3440"
format = '[[($staged$modified$deleted$untracked$ahead_behind )](bg:#2e3440)]($style)'
staged = '[+$count](fg:#a3be8c bg:#2e3440)'
modified = '[~$count](fg:#ebcb8b bg:#2e3440)'
deleted = '[!$count](fg:#bf616a bg:#2e3440)'
untracked = '[?$count](fg:#616e88 bg:#2e3440)'
ahead = '[⇡$count](fg:#a3be8c bg:#2e3440)'
behind = '[⇣$count](fg:#bf616a bg:#2e3440)'
diverged = '[⇡$ahead_count⇣$behind_count](fg:#d08770 bg:#2e3440)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[$duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#2e3440"
format = '[[   $time ](fg:#a0a9cb)]($style)'

[character]
vimcmd_symbol = '[V](bold green) '
